### PR TITLE
add flux mini submit piped into attach

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
okay this doesn't immediately work - but we will eventually want to be able to pipe output as it comes with something like attach.

**Comment by grondo** [comment]
Not sure if this helps, but `flux mini submit` has a `--watch` option that will cause the command to wait until the job finishes and will copy output to stdout/err as an alternative to executing a separate `flux job attach`.

**Comment by vsoch** [comment]
@grondo that might be what we want! Is `--watch` going to show it in real time, or just do one dump at the end when it finishes? I think we are interested in showing real time, the reason being with large jobs you are sort of waiting and wondering if it's working.

**Comment by grondo** [comment]
`--watch` shows the output in real time

**Comment by vsoch** [comment]
okay that was me, I added a bug, going to fix it!

**Comment by vsoch** [comment]
This is my theme song! https://www.youtube.com/watch?v=b1kbLwvqugk :laughing:

**Comment by vsoch** [comment]
It looks like that spits out the flux job id too - is that expected?

```
ctual:
ƒdNfP1h
LAMMPS (29 Sep 2021 - Update 2)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
```
So I understand - the difference between `flux mini submit --watch` and `flux mini run` is that the first prints the jobid and then streams stdout/stderr in real time, vs. the second doesn't print the job id, and dumps the stdout/stderr at the end?

**Comment by vsoch** [comment]
I would think `flux mini run` does what `--watch` maybe does, per:

image

I'm currently searching for how to silence the jobid.

**Comment by grondo** [comment]
Yeah, `flux mini run` will behave quite similarly to `flux mini submit --watch --quiet`, but it execs `flux job attach` to handle the output. Note that `flux mini submit` can't currently handle stdin. The main benefit of `flux mini submit --watch` (besides the fact that it is a single proces) is that it can handle "watching" multiple jobs submitted at once with `--cc/--bcc` or via `flux mini bulksubmit` (along with a nifty `--progress` option)

**Comment by vsoch** [comment]
> Note that flux mini submit can't currently handle stdin. 

So this would be, for example, if that job asked for human interaction? E.g., "Enter y/n" I don't foresee needing that for these jobs, at least for now!

**Pull request merged**
